on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Build ISO
    description: 'Build the Akoziland core iso.'
    steps:
      runs:
        using: 'docker'
        image: 'Dockerfile'
